---
version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "markmcdowell"
    commit_message:
      prefix: "chore"
      include_scope: true
